toolbar:
  - undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist | image | link
plugins:
  - image
  - link
  - lists
setup :
  function(ed) {
    ed.on('init', function() 
    {
        this.getDoc().body.style.fontSize = '14px';
        this.getDoc().body.style.color = '#626262';
    });
  }